name: bonsoir_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bonsoir: ^5.0.3
  uuid: ^4.2.1
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  network_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
